import React, { useEffect, useState, useRef } from "react";
import axios from "axios";
import { Button, Spinner, Card, CardBody, CardHeader } from "reactstrap";
import { useUser } from "../../context/UserContext";
import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { Link } from "react-router-dom";
import { API_URL } from "../../constants";
import SubjectBarChart from "./SubjectBarChart";

const StudentResults = () => {
  const { userData } = useUser();
  const [examMarks, setExamMarks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [finalPercentage, setFinalPercentage] = useState(0);
  const [finalStatus, setFinalStatus] = useState("");
  const contentRef = useRef(null);

  useEffect(() => {
    const fetchExamMarks = async () => {
      try {
        const response = await axios.get(
          `${API_URL}/api/exam_marks/${userData._id}`
        );

        setExamMarks(response.data.examMarks);
        setFinalPercentage(response.data.finalPercentage);
        setFinalStatus(response.data.finalStatus);
        setLoading(false);
      } catch (error) {
        console.error("Error fetching exam marks:", error);
        setLoading(false);
        // Handle error fetching data
      }
    };

    fetchExamMarks();
  }, [userData._id]);

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
  
    // School Header
    doc.setFontSize(22);
    doc.text("Springfield High School", 105, 20, { align: "center" });
    doc.setFontSize(12);
    doc.text("123 Education Street, Knowledge City", 105, 28, { align: "center" });
    doc.text("Phone: (123) 456-7890 | Email: contact@springfieldschool.edu", 105, 34, { align: "center" });
    doc.line(14, 38, 196, 38); // Draw a line below the header
  
    // Student Details
    doc.setFontSize(14);
    doc.text(`Name: ${userData.fullName}`, 14, 50);
    doc.text(`Email: ${userData.email || "N/A"}`, 14, 60);
    doc.text(`Gender: ${userData.gender || "N/A"}`, 14, 70);
    doc.text(`Year: ${new Date().getFullYear()}`, 14, 80);
  
    // Subject-wise Marks Table
    let position = 90;
    Object.keys(groupedMarks).forEach((courseName) => {
      doc.setFontSize(16);
      doc.text(courseName, 14, position);
  
      const tableData = groupedMarks[courseName].map((mark, index) => [
        index + 1,
        `${new Date(mark.timestamp).toLocaleDateString()}`,
        `${mark.marks} / ${Object.keys(mark.answers).length}`,
        `${mark.percentage.toFixed(2)}%`,
        `${mark.passFailStatus}`,
        `${mark.grade}`,
      ]);
  
      doc.autoTable({
        startY: position + 10,
        head: [["#", "Date", "Marks", "Percentage", "Status", "Grade"]],
        body: tableData,
        theme: "grid",
        headStyles: { fillColor: [0, 102, 204] },
        bodyStyles: { fontSize: 10 },
      });
  
      position = doc.autoTable.previous.finalY + 10;
    });
  
    // Overall Summary
    doc.setFontSize(16);
    doc.text("Summary", 14, position);
    doc.autoTable({
      startY: position + 10,
      body: [
        ["Final Percentage", `${finalPercentage.toFixed(2)}%`],
        ["Final Status", `${finalStatus}`],
        ["Remarks", finalPercentage >= 50 ? "Passed" : "Needs Improvement"],
      ],
      theme: "plain",
      styles: { fontSize: 12, halign: "right" },
    });
  
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.text("Generated by Springfield High School", 105, pageHeight - 10, { align: "center" });
  
    // Save the PDF
    doc.save(`student_results_${userData.fullName}.pdf`);
  };
  

  const groupedMarks = examMarks.reduce((acc, mark) => {
    if (!acc[mark.courseName]) {
      acc[mark.courseName] = [];
    }
    acc[mark.courseName].push(mark);
    return acc;
  }, {});

  return (
    <div className="container text-center margin-top-bottom">
      <div className="col-md-8 offset-md-2 min-vh-100" ref={contentRef}>
        <h2 className="m-5 display-6">Student Results</h2>

        <p className="fs-5 mb-5">
          Hello, {userData.fullName}. Your Results are as follows:
        </p>

        {loading ? (
          <div className="text-center margin-top-bottom">
            <Spinner
              color="primary"
              style={{
                height: "3rem",
                width: "3rem",
              }}
            >
              Loading...
            </Spinner>
          </div>
        ) : Object.keys(groupedMarks).length === 0 ? (
          <p className="fs-5 mt-5 animated-text">No exam marks found.</p>
        ) : (
          <div className="row row-cols-1 row-cols-md-1 g-3 mt-2">
            {Object.keys(groupedMarks).map((courseName) => (
              <div key={courseName} className="col">
                {groupedMarks[courseName].map((mark) => (
                  <Link
                    key={mark._id}
                    to={`/exam/${encodeURIComponent(courseName)}`}
                    className="text-decoration-none"
                  >
                    <Card className="mb-4">
                      <CardHeader>
                        <h4>{courseName}</h4>
                      </CardHeader>
                      <CardBody>
                        <p className="card-text">
                          Submitted on{" "}
                          {new Date(mark.timestamp).toLocaleDateString()} at{" "}
                          {new Date(mark.timestamp).toLocaleTimeString()}
                        </p>
                        <p className="card-text">
                          <strong>Marks:</strong> {mark.marks} out of{" "}
                          {Object.keys(mark.answers).length}
                        </p>
                        <p className="card-text">
                          <strong>Percentage:</strong> {mark.percentage}%
                        </p>
                        <p className="card-text">
                          <strong>Status:</strong> {mark.passFailStatus}
                        </p>
                        <p className="card-text">
                          <strong>Grade:</strong> {mark.grade}
                        </p>
                      </CardBody>
                    </Card>
                  </Link>
                ))}
              </div>
            ))}
          </div>
        )}

        {Object.keys(groupedMarks).length !== 0 && (
          <>
            <div className="mt-5">
              <h4 className="text-center">Overall Results</h4>
              <p className="text-center">
                Final Percentage: {finalPercentage.toFixed(2)}%
              </p>
              <p className="text-center">Final Status: {finalStatus}</p>
            </div>

            <div className="text-center mt-3 mb-5">
              <Button color="primary" onClick={handleDownloadPDF}>
                Download Results as PDF
              </Button>
            </div>
          </>
        )}

        <SubjectBarChart />
      </div>
    </div>
  );
};

export default StudentResults;
